### ISSUE TITLE
SPACES IN THE URLS OMG

### ISSUE THREAD

**Issue by dpzmick** [illinois-cs/illinois-cs.github.io#1]
http://localhost:4000/Pointers%20Gone%20Wild

are we okay with spaces?

**Comment by lotrfan** [comment]
I'm not a fan... not that that really matters, though.

Is hosting on github pages a temporary thing and/or a mirror and/or for testing? I feel like the primary location should be on an illinois.edu server...

**Comment by earwig** [comment]
Yeah, I'm definitely not a fan of the spaces either.

**Comment by dpzmick** [comment]
I wish it said that brandon closed this. He opened the PR, I just hit merge..
